/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiRemoveBgRouteImport } from './routes/api/remove-bg'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api/razorpay/webhook'
import { Route as ApiRazorpayVerifyPaymentRouteImport } from './routes/api/razorpay/verify-payment'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBgRoute = ApiRemoveBgRouteImport.update({
  id: '/api/remove-bg',
  path: '/api/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay/webhook',
  path: '/api/razorpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyPaymentRoute =
  ApiRazorpayVerifyPaymentRouteImport.update({
    id: '/api/razorpay/verify-payment',
    path: '/api/razorpay/verify-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/remove-bg': typeof ApiRemoveBgRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify-payment': typeof ApiRazorpayVerifyPaymentRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/create-order'
    | '/api/remove-bg'
    | '/api/verify-payment'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/create-order'
    | '/api/remove-bg'
    | '/api/verify-payment'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/create-order'
    | '/api/remove-bg'
    | '/api/verify-payment'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify-payment'
    | '/api/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiRemoveBgRoute: typeof ApiRemoveBgRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayVerifyPaymentRoute: typeof ApiRazorpayVerifyPaymentRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-bg': {
      id: '/api/remove-bg'
      path: '/api/remove-bg'
      fullPath: '/api/remove-bg'
      preLoaderRoute: typeof ApiRemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/webhook': {
      id: '/api/razorpay/webhook'
      path: '/api/razorpay/webhook'
      fullPath: '/api/razorpay/webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify-payment': {
      id: '/api/razorpay/verify-payment'
      path: '/api/razorpay/verify-payment'
      fullPath: '/api/razorpay/verify-payment'
      preLoaderRoute: typeof ApiRazorpayVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiRemoveBgRoute: ApiRemoveBgRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayVerifyPaymentRoute: ApiRazorpayVerifyPaymentRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
